# ===========================
# LiteLLM Proxy config (Azure)
# ===========================
litellm_settings:
  set_verbose: true
  drop_params: true
  callbacks: ["langfuse_otel"]
  success_callback: ["langfuse_otel"]

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

# ---------------------------
# Models exposed by the proxy
# ---------------------------
model_list:
  # ===== GPT-5 Series =====
  - model_name: gpt-5
    litellm_params:
      model: azure/gpt-5
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5

  - model_name: gpt-5-test
    litellm_params:
      model: azure/gpt-5
      api_base: os.environ/AZURE_API_BASE_TEST
      api_version: "latest"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5      

  - model_name: gpt-5-chat
    litellm_params:
      model: azure/gpt-5-chat
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5

  - model_name: gpt-5-codex
    litellm_params:
      model: azure/gpt-5-codex
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5

  - model_name: gpt-5-mini
    litellm_params:
      model: azure/gpt-5-mini
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5-mini

  - model_name: gpt-5-nano
    litellm_params:
      model: azure/gpt-5-nano
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-5-nano

  # ===== GPT-4.1 / 4o =====
  - model_name: gpt-4.1
    litellm_params:
      model: azure/gpt-4.1
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-4.1

  - model_name: gpt-4.1-mini
    litellm_params:
      model: azure/gpt-4.1-mini
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-4.1-mini

  - model_name: gpt-4.1-nano
    litellm_params:
      model: azure/gpt-4.1-nano
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-4.1-nano

  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-4o

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_API_BASE
      api_version: "preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: gpt-4o-mini

  - model_name: gpt-4o-mini-tts
    litellm_params:
      model: azure/gpt-4o-mini-tts
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      mode: tts
      base_model: gpt-4o-mini-tts

  # ===== O-Series =====
  - model_name: o1
    litellm_params:
      model: azure/o_series/o1
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: o1

  - model_name: o3
    litellm_params:
      model: azure/o_series/o3
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: o3

  - model_name: o3-mini
    litellm_params:
      model: azure/o_series/o3-mini
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: o3-mini

  - model_name: o4-mini
    litellm_params:
      model: azure/o_series/o4-mini
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: o4-mini

  # ===== Images / Embeddings =====
  - model_name: gpt-image-1
    litellm_params:
      model: azure/gpt-image-1
      api_base: os.environ/AZURE_API_BASE_IMAGES
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY_IMAGES
    model_info:
      mode: image_generation
      base_model: dall-e-3

  - model_name: text-embedding-3-large
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      mode: embeddings
      base_model: text-embedding-3-large

  - model_name: text-embedding-3-small
    litellm_params:
      model: azure/text-embedding-3-small
      api_base: os.environ/AZURE_API_BASE
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
    model_info:
      mode: embeddings
      base_model: text-embedding-3-small

# ---------------------------
# Routing defaults
# ---------------------------
router_settings:
  default_model: gpt-4o
